=== uo287577/sew/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="galeria" />
				<xs:element ref="coordenadas" />
				<xs:element ref="puntos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades_longitud" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidades_anchura" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:positiveInteger" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="referencia" minOccurs="3" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeria">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" minOccurs="3" maxOccurs="3"/>
			</xs:sequence>
			<xs:attribute name="pertenencia" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="tipo" type="tipoCoordenada" use="required" />
					<xs:attribute name="unidad" type="unidadCoordenada" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoCoordenada">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Longitud" />
			<xs:enumeration value="Latitud" />
			<xs:enumeration value="Altitud" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="unidadCoordenada">
		<xs:restriction base="xs:string">
			<xs:enumeration value="metros" />
			<xs:enumeration value="grados" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
			<xs:attribute name="numero_tramo" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades_distancia" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector">
		<xs:complexType>
			<xs:attribute name="numero_sector" type="xs:positiveInteger" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uo287577/sew/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<circuito 
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>"Barcelona-Catalunya"</nombre>
    <longitud unidades_longitud="km">4.657</longitud>
    <anchura unidades_anchura="m">12</anchura>
    <fecha>2024-06-23</fecha>
    <hora>15:00:00</hora>
    <vueltas>66</vueltas>
    <localidad>"Montmeló"</localidad>
    <pais>"España"</pais>
    <referencias>
        <referencia>"https://es.wikipedia.org/wiki/Circuito_de_Barcelona-Catalu%C3%B1a"</referencia>
        <referencia>"https://desdelapelouse.wordpress.com/2012/05/11/circuit-de-catalunya/"</referencia>
        <referencia>"https://www.circuitcat.com/es/#:~:text=Situado%20en%20Montmel%C3%B3%2C%20el%20Circuit,y%20el%20Ayuntamiento%20de%20Montmel%C3%B3."</referencia>
    </referencias>
    <galeria>
        <fotos>
            <foto>"Foto_circuito_1.jpg"</foto>
        </fotos>
        <videos>
        </videos>
    </galeria>
    <coordenadas pertenencia="Línea de salida del circuito">
        <coordenada tipo="Longitud" unidad="grados">2.261216°E</coordenada>
        <coordenada tipo="Latitud" unidad="grados">41.570023°N</coordenada>
        <coordenada tipo="Altitud" unidad="metros">120.0</coordenada>
    </coordenadas>
    <puntos>
        <tramo numero_tramo="1">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256822°E</coordenada> 
                <coordenada tipo="Latitud" unidad="grados">41.564792°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <!--PUNTOS INTERMEDIOS CURVA 1-->
        <tramo numero_tramo="2">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256712°E</coordenada>
                <coordenada tipo="Latitud" unidad="grados">41.564695°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="3">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256610°E</coordenada>  
                <coordenada tipo="Latitud" unidad="grados">41.564650°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">111.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="4">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256499°E</coordenada>   
                <coordenada tipo="Latitud" unidad="grados">41.564629°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="5">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256386°E</coordenada>    
                <coordenada tipo="Latitud" unidad="grados">41.564624°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="6">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256282°E</coordenada> 
                <coordenada tipo="Latitud" unidad="grados">41.564638°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="7">
            <distancia unidades_distancia="m">684.72</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud" unidad="grados">2.256182°E</coordenada>  
                <coordenada tipo="Latitud" unidad="grados">41.564671°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <!--..........................-->
        <tramo numero_tramo="2"> <!--Final de la curva-->
            <distancia unidades_distancia="m">69.24</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.256114°E</coordenada> 
                <coordenada tipo="Latitud" unidad="grados">41.564710°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">111.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="3">
            <distancia unidades_distancia="m">16.81</distancia> <!--Mini recta de la chicane-->
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255902°E</coordenada>  
                <coordenada tipo="Latitud" unidad="grados">41.564804°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">112.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <!--PUNTOS INTERMEDIOS DE LA CURVA 2-->
        <tramo numero_tramo="4">
            <distancia unidades_distancia="m">78.36</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255807°E</coordenada>  
                <coordenada tipo="Latitud" unidad="grados">41.564850°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">113.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="5">
            <distancia unidades_distancia="m">78.36</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255696°E</coordenada>    
                <coordenada tipo="Latitud" unidad="grados">41.564883°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">113.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="6">
            <distancia unidades_distancia="m">78.36</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255579°E</coordenada>      
                <coordenada tipo="Latitud" unidad="grados">41.564899°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">113.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="7">
            <distancia unidades_distancia="m">78.36</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255412°E</coordenada>        
                <coordenada tipo="Latitud" unidad="grados">41.564903°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">113.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="8">
            <distancia unidades_distancia="m">78.36</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255139°E</coordenada>     
                <coordenada tipo="Latitud" unidad="grados">41.564836°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">114.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <!--.................................-->
        <tramo numero_tramo="4">
            <distancia unidades_distancia="m">78.36</distancia> <!--final de la curva 2-->  
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.255040°E</coordenada>  
                <coordenada tipo="Latitud" unidad="grados">41.564790°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">115.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="5">
            <distancia unidades_distancia="m">68.54</distancia> <!--La recta antes de la curva larga del principio-->
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.254354°E</coordenada> 
                <coordenada tipo="Latitud" unidad="grados">41.564400°N</coordenada>
                <coordenada tipo="Altitud" unidad="metros">118.0</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <!--PUNTOS INTERMEDIOS DE LA CURVA LARGA DEL PRINCIPIO-->
        <tramo numero_tramo="6">
            <distancia unidades_distancia="m">405.62</distancia>  
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud" unidad="grados">2.254104°E</coordenada>
