=== uo287577/sew/F1Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre,longitud,anchura,fecha,hora,vueltas,localidad,pais,referencias,galeria,coordenadas,puntos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT referencias (referencia,referencia,referencia)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT galeria (fotos,videos)>
<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT coordenadas (coordenada,coordenada,coordenada)>
<!ELEMENT coordenada (#PCDATA)>
<!ELEMENT puntos (tramo+)>
<!ELEMENT tramo (distancia,coordenadas,sector)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT sector (#PCDATA)>
<!ATTLIST longitud unidades_longitud CDATA #REQUIRED>
<!ATTLIST anchura unidades_anchura CDATA #REQUIRED>
<!ATTLIST coordenadas pertenencia CDATA #REQUIRED>
<!ATTLIST coordenada tipo CDATA #REQUIRED>
<!ATTLIST tramo numero_tramo CDATA #REQUIRED>
<!ATTLIST distancia unidades_distancia CDATA #REQUIRED>
<!ATTLIST sector numero_sector CDATA #REQUIRED>

=== uo287577/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>"Barcelona-Catalunya"</nombre>
    <longitud unidades_longitud="km">"4,657"</longitud>
    <anchura unidades_anchura="m">"12"</anchura>
    <fecha>"23/06/2024"</fecha>
    <hora>"15:00h"</hora>
    <vueltas>"66"</vueltas>
    <localidad>"Montmeló"</localidad>
    <pais>"España"</pais>
    <referencias>
        <referencia>"https://es.wikipedia.org/wiki/Circuito_de_Barcelona-Catalu%C3%B1a"</referencia>
        <referencia>"https://desdelapelouse.wordpress.com/2012/05/11/circuit-de-catalunya/"</referencia>
        <referencia>"https://www.circuitcat.com/es/#:~:text=Situado%20en%20Montmel%C3%B3%2C%20el%20Circuit,y%20el%20Ayuntamiento%20de%20Montmel%C3%B3."</referencia>
    </referencias>
    <galeria>
        <fotos>
            <foto>"Foto_circuito_1.jpg"</foto>
        </fotos>
        <videos>
        </videos>
    </galeria>
    <coordenadas pertenencia="Línea de salida del circuito">
        <coordenada tipo="Longitud">"2°15'40"E"</coordenada>
        <coordenada tipo="Latitud">"41°34'12"N"</coordenada>
        <coordenada tipo="Altitud">"120m"</coordenada>
    </coordenadas>
    <puntos>
        <tramo numero_tramo="1">
            <distancia unidades_distancia="m">"684,72"</distancia>
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud">"2°15'24"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'53"N"</coordenada>
                <coordenada tipo="Altitud">"112m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="2">
            <distancia unidades_distancia="m">"69,24"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'23"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'53"N"</coordenada>
                <coordenada tipo="Altitud">"111m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="3">
            <distancia unidades_distancia="m">"16,81"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'21"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'53"N"</coordenada>
                <coordenada tipo="Altitud">"112m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="4">
            <distancia unidades_distancia="m">"78,36"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'18"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'53"N"</coordenada>
                <coordenada tipo="Altitud">"115m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="5">
            <distancia unidades_distancia="m">"68,54"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'15"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'51"N"</coordenada>
                <coordenada tipo="Altitud">"118m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="6">
            <distancia unidades_distancia="m">"405,62"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'10"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'59"N"</coordenada>
                <coordenada tipo="Altitud">"128m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="7">
            <distancia unidades_distancia="m">"222,9"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'14"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'05"N"</coordenada>
                <coordenada tipo="Altitud">"131m"</coordenada>
            </coordenadas>
            <sector numero_sector="1"/>
        </tramo>
        <tramo numero_tramo="8">
            <distancia unidades_distancia="m">"232,3"</distancia>
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'16"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'58"N"</coordenada>
                <coordenada tipo="Altitud">"133m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="9">
            <distancia unidades_distancia="m">"182,68"</distancia> <!--(recta antes de la curva que se hace en segunda)-->
            <coordenadas pertenencia="Final del tramo"> 
                <coordenada tipo="Longitud">"2°15'14"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'56"N"</coordenada>
                <coordenada tipo="Altitud">"129m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="10">
            <distancia unidades_distancia="m">"92,53"</distancia> <!--(la curva que se hace en segunda)-->
            <coordenadas pertenencia="Final del tramo">  
                <coordenada tipo="Longitud">"2°15'16"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'55"N"</coordenada>
                <coordenada tipo="Altitud">"124m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="11">
            <distancia unidades_distancia="m">"154,32"</distancia> <!--(la recta justo despues de la curva que se hace en segunda)-->
            <coordenadas pertenencia="Final del tramo">  
                <coordenada tipo="Longitud">"2°15'21"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'58"N"</coordenada>
                <coordenada tipo="Altitud">"120m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="12">
            <distancia unidades_distancia="m">"81,1"</distancia> <!--(curva 6 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'25"E"</coordenada>
                <coordenada tipo="Latitud">"41°33'58"N"</coordenada>
                <coordenada tipo="Altitud">"119m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="13">
            <distancia unidades_distancia="m">"113,44"</distancia> <!--(recta justo despues de la curva 6 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">  
                <coordenada tipo="Longitud">"2°15'27"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'01"N"</coordenada>
                <coordenada tipo="Altitud">"115m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="14">
            <distancia unidades_distancia="m">"70,98"</distancia> <!--(curva 7 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">  
                <coordenada tipo="Longitud">"2°15'27"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'03"N"</coordenada>
                <coordenada tipo="Altitud">"115m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="15">
            <distancia unidades_distancia="m">"27,35"</distancia> <!--(recta justo despues de la curva 7 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">   
                <coordenada tipo="Longitud">"2°15'26"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'04"N"</coordenada>
                <coordenada tipo="Altitud">"119m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="16">
            <distancia unidades_distancia="m">"45,58"</distancia> <!--(curva 8 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'24"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'05"N"</coordenada>
                <coordenada tipo="Altitud">"122m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="17">
            <distancia unidades_distancia="m">"183,11"</distancia> <!--(recta justo despues de la curva 8 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'21"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'10"N"</coordenada>
                <coordenada tipo="Altitud">"132m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="18">
            <distancia unidades_distancia="m">"137,38"</distancia> <!--(curva 9 del layout oficial)-->
            <coordenadas pertenencia="Final del tramo">
                <coordenada tipo="Longitud">"2°15'23"E"</coordenada>
                <coordenada tipo="Latitud">"41°34'14"N"</coordenada>
                <coordenada tipo="Altitud">"136m"</coordenada>
            </coordenadas>
            <sector numero_sector="2"/>
        </tramo>
        <tramo numero_tramo="19">
